version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROXY=
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - ALL_PROXY=
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

networks:
  default:
    driver: bridge